# --------------------------------------------------
# Ensure ~/Pictures exists
# --------------------------------------------------
- name: Ensure Pictures directory exists
  become: true
  file:
    path: "/home/{{ ansible_env.SUDO_USER }}/Pictures"
    state: directory
    owner: "{{ ansible_env.SUDO_USER }}"
    group: "{{ ansible_env.SUDO_USER }}"
    mode: '0755'

# --------------------------------------------------
# Copy all pictures
# --------------------------------------------------
- name: Copy wallpapers to Pictures
  become: true
  copy:
    src: Pictures/
    dest: "/home/{{ ansible_env.SUDO_USER }}/Pictures/"
    owner: "{{ ansible_env.SUDO_USER }}"
    group: "{{ ansible_env.SUDO_USER }}"
    mode: '0644'

